### PR TITLE
Create dashboard-results.json

### PR DESCRIPTION
**Pull request by matentzn**

### CODE REVIEW

**Review by anitacaron — APPROVED** [review]

**Comment by anitacaron** [comment]
Maybe better to update it with the dashboard release?

**Comment by anitacaron** [comment]
Can you manually update the json for now? I don't have yq installed.

**Comment by matentzn** [comment]
Done. thanks! Dont worry about merging this PR without #16 addressed, its a good reminder that we need it

**Comment by anitacaron** [comment]
Yeah, we could merge this PR for now, and then address the issue later.

**Comment by matentzn** [comment]
No need, James is using the branch raw.github URL, so right now we can just leave it open

**Comment by anitacaron** [comment]
This was done in PR https://github.com/OBOFoundry/OBO-Dashboard/pull/114

**Pull request closed without merging**
